---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
set.seed(8675309)
```

# Data Simulation Workshop Materials

## Workshops

### 20/01/28 Introduction to Data Simulation in R

When: Tuesday Jan 28 13:00-15:00  
Where: Boyd Orr Room 603 

#### Prep

* Install R packages from CRAN: `tidyverse`, `afex`, `lme4`, `broom`, `broom.mixed`, `kableExtra`
* Install development R package: `faux`
    - `devtools::install_github("debruine/faux")`
    - (you might need to install `devtools` first)
* Download files (stub versions have instructions but only skeleton code for you to fill in during the workshop)
    - [fixed-effects.Rmd](https://osf.io/9xghp/download)
    - [fixed-effects-stub.Rmd](https://osf.io/efqwm/download)
    - [faux.Rmd](https://osf.io/wa58r/download)
    - [faux-stub.Rmd](https://osf.io/xwcpy/download)

### 20/02/05 Understanding Mixed-Effects Models through Data Simulation

When: Wednesday Feb 5 14:00-16:00  
Where: Boyd Orr Room 603

#### Prep

* Install R packages from CRAN: `tidyverse`, `afex`, `lme4`, `broom`, `broom.mixed`, `kableExtra`
* Install development R package: `faux`
    - `devtools::install_github("debruine/faux")`
* Download files (stub versions have instructions but only skeleton code for you to fill in during the workshop)
    - [mixed-effects.Rmd] (https://osf.io/vf3ca/download)
    - [mixed-effects-stub.Rmd]()

## Resources

* [Data Skills for Reproducible Science](https://psyteachr.github.io/msc-data-skills/) open source textbook introducing tidyverse for psychologists
* [Understanding mixed effects models through data simulation](https://osf.io/3cz2e/) (preprint, code, and shiny apps)

